### ISSUE TITLE
Feat: 배포 개발 서버 분리

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#103]
## 📌 Feature Issue

* 배포 개발 서버 분리

## 📝 To-do
- [x] 배포 서버 인프라 구축
- [x] application.yml 분리
- [x] ci/cd 분리

## 💡 ETC

>
