### ISSUE TITLE
Feat: 회원 세부 정보 추가

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#11]
## 📌 Feature Issue

* 회원 관련 세부 사항 및 추가 정보 구현

## 📝 To-do
- [x] S3 설정
- [x] 회원 가입 후 바로 로그인 진행
- [x] 회원 프로필 사진 추가
- [x] 회원 성별 추가
- [x] 회원 전화번호 삭제
- [x] 닉네임 초기 설정 API 추가
- [x] 알레르기 초기 설정 API 추가
- [x] 질병 초기 설정 API 추가

## 💡 ETC

>
