### ISSUE TITLE
Feat: 알약 검색 기능 추가

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#110]
## 📌 Feature Issue

* 알약 검색 시 필터 정보 추가 및 이미지 검색 추가

## 📝 To-do
- [x] 알약 검색 시 검색 결과에 필터 정보 추가
- [x] AI 서버 연결
- [x] 이미지 검색 API 추가

## 💡 ETC

>
