### ISSUE TITLE
Feat: 마이페이지

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#13]
## 📌 Feature Issue

* 마이페이지 API 작업

## 📝 To-do
- [x] 내 알레르기 및 질병 정보 제공
- [x] 내 알레르기 및 질병 정보 수정
- [x] 내가 복용 중인 약 정보 제공
- [x] 내가 복용 중인 약 수정
- [x] 정보 수정

## 💡 ETC

>
