### ISSUE TITLE
Feat: 즐겨찾기 및 최근 본 알약 정보

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#16]
## 📌 Feature Issue

* 즐겨찾기 및 최근 본 알약 정보

## 📝 To-do
- [x] mongo DB 설정
- [x] 즐겨찾기 추가 및 삭제
- [x] 즐겨찾기 조회
- [x] 최근 본 알약 정보 collection 추가
- [x] 최근 본 알약 정보 추가
- [x] 최근 본 알약 정보 삭제
- [x] 최근 본 알약 정보 조회
- [x]  <s>검색 기록 추가</s>

## 💡 ETC

> 검색 기록은 프론트 팀에서 구현하기로 하였습니다.
