### ISSUE TITLE
Feat: 알약 정보 수정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#17]
## 📌 Feature Issue

* 알약 정보 조회 시 관련 질병 알레르기 정보 전송

## 📝 To-do
- [x] 알약 정보 조회 API에 경고 내용 추가
- [x] 관련 Swagger 추가
- [x] 알약 검색 리스트 결과에 제조 업체 및 성상 정보 추가
- [x] 알약 검색 시 경고 여부 로직 수정

## 💡 ETC

>
