### ISSUE TITLE
Feat: CI/CD 설정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#19]
## 📌 Feature Issue

* Jenkins 및 Docker를 다중서버 무중단 배포 CI/CD 설정

## 📝 To-do
- [x] Jenkins 서버 설정
- [x] Jenkins 및 Docker 설치
- [x] 서버 등록
- [x] Github 등록
- [x] Pipeline 생성 및 스크립트 작성
- [x] 배포 스크립트 작성
- [x] ci/cd 테스트

## 💡 ETC

>
