### ISSUE TITLE
Feat: 서버 배포

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#20]
## 📌 Feature Issue

* Spring boot, MySQL, Mongo db, Redis 서버 배포

## 📝 To-do
- [x] VPC 설정
- [x] EC2 인스턴스 설정
- [x] RDS MySQL 데이터베이스 설정
- [x] Mongo Atlas 설정
- [x] ElastiCache Redis 설정

## 💡 ETC

>
