### ISSUE TITLE
Feat: Swagger 설정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#25]
## 📌 Feature Issue

* Api 및 Request, Respone DTO Swagger 설정

## 📝 To-do
- [x] searchController Swagger 설정
- [x] favoriteController Swagger 설정
- [x] Auth Dto Swagger 설정
- [x] OAuth Dto Swagger 설정
- [x] Member Dto Swagger 설정
- [x] Health Dto Swagger 설정
- [x] Search Dto Swagger 설정
- [x] Favorite Dto Swagger 설정

## 💡 ETC

>
