### ISSUE TITLE
Reafactor: 회원 관련 정보 수정 및 API 생성

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#26]
## 📌 Feature Issue

* 회원 가입 시 성별 저장 방식 통일 및 소셜 회원가입 광고 여부 추가

## 📝 To-do
- [x] 성별 ENUM 설정
- [x] 소셜 회원가입 시 성별 통일
- [x] 소셜 회원가입 시 광고 여부 추가
- [x] 회원 기본 정보 제공 API
- [x] 회원 가입 수정 전 비밀번호 인증 API
- [x] 회원 상세 정보 제공 API

## 💡 ETC

>
