### ISSUE TITLE
Feat: 알약 정보 글 태그 삭제

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#35]
## 📌 Feature Issue

* 알약 정보 XML 문서 파싱

## 📝 To-do
- [x] XML 문서 구현체 클래스 생성
- [x] XML 파싱 함수 구현
- [x] XML 문서 파싱
- [x] DTO 구분

## 💡 ETC

>
