### ISSUE TITLE
Feat: validation 및 swagger 수정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#44]
## 📌 Feature Issue

* validation 및 swagger 문구 수정

## 📝 To-do
- [x] Tag 표시 방법 변경
- [x] 토큰 인증 필요 API 표시 방법 변경
- [x] swagger 예시 추가
- [x] OAuth 주소 추가
- [x] request validation 확인
- [x] validation 어노테이션 추가

## 💡 ETC

>
