### ISSUE TITLE
Feat: 요구 사항에 변경에 따른 이미지 검색 및 맴버 기능 수정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#45]
## 📌 Feature Issue

* 요구사항 변경에 따른 이미지 검색 및 맴버 기능 수정

## 📝 To-do
- [x] 이미지 검색 필터 기능 삭제
- [x] 이미지 검색 리스트로 이미지 받아오기
- [x] 닉네임 기능 삭제

## 💡 ETC

>
