### ISSUE TITLE
Feat: 복용중인 알약 카테고리 기능 추가

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#55]
## 📌 Feature Issue

* 복용중인 알약에 카테고리 기능 추가

## 📝 To-do
- [x] 카테고리 기능 추가에 따른 엔티티 수정
- [x] 카테고리 CRUD API
- [x] 복용중인 알약 이동 API
- [x] 복용중인 알약 조회 API
- [x] 스웨거 및 validation 작업

## 💡 ETC

>
