### ISSUE TITLE
Feat: 캘린더 설정 API 추가

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#63]
## 📌 Feature Issue

* 캘린더 설정 API 추가

## 📝 To-do
- [x] 캘린더 Entity 추가
- [x] 캘린더 설정 도메인
- [x] 캘린더 설정 API
- [x] validation 및 swagger 설정

## 💡 ETC

>
