### ISSUE TITLE
Feat: CI/CD 방식 변경

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#93]
## 📌 Feature Issue

*  기존에 Jenkins를 사용하여 구축한 CI/CD 방식을 Github Action으로 변경

## 📝 To-do
- [x] workflow 파일 생성
- [x] secrets 설정
- [x] DockerFile 파일 생성
- [x] deploy 파일 샐성
- [x] Github Action self-hosted runners 설정
- [x] Nginx 설정
- [x] Docker 설

## 💡 ETC

> 참고사이트 : [Github Action 무중단 배포](https://engineerinsight.tistory.com/265#%F0%9F%92%8B%C2%A0Github%20Actions%20workflow%20%EC%83%9D%EC%84%B1-1)
