### ISSUE TITLE
Refactor: 알약 검색 속도 개선

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#95]
## 📌 Feature Issue

* 알약 주의 사항을 DB에 저장하여 검색 시 경고 표시를 위해 알약의 주의 사항을 API를 통해 호출하는 과정 간소화

## 📝 To-do
- [ ] 알약 주의 사항 데이터 전처리
- [ ] DB 데이터 업데이트
- [ ] 알약 주의 사항 호출 로직 수정

## 💡 ETC

>
