### ISSUE TITLE
Feat: 로깅 설정

### ISSUE THREAD

**Issue by ckdals4600** [baeksaitong/SOFP_BACK#98]
## 📌 Feature Issue

* 로깅 작업 및 cloud watch 연결

## 📝 To-do
- [x] 로그 작업
- [x] 운영, 개발, 로컬 환경 분리
- [x] cloud watch 설정
- [x] discord bot 설정

## 💡 ETC

>
